<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>nas-deduplicator-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <!-- Fully exclude the test project from the main application build -->
    <Compile Remove="NASdeduplication.Tests\**" />
    <Content Remove="NASdeduplication.Tests\**" />
    <EmbeddedResource Remove="NASdeduplication.Tests\**" />
    <None Remove="NASdeduplication.Tests\**" />
  </ItemGroup>

</Project>
